-- 00_account_setup.sql
-- Account-level objects: warehouses, database, schemas, roles, RBAC grants.
-- Run as ACCOUNTADMIN (or a role with CREATE WAREHOUSE / CREATE DATABASE / CREATE ROLE).
-- Idempotent: safe to re-run.

USE ROLE ACCOUNTADMIN;

------------------------------------------------------------------------------
-- Warehouses  (small, auto-suspending — cost first)
------------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS RB_LOAD_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Staging PUT + COPY INTO RAW';

CREATE WAREHOUSE IF NOT EXISTS RB_TRANSFORM_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'dbt staging + marts builds';

CREATE WAREHOUSE IF NOT EXISTS RB_BI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Analyst / BI queries';

------------------------------------------------------------------------------
-- Database + schemas  (RAW immutable, STAGING cleans, MARTS serves, UTIL ops)
------------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS REDBULL_DELIVERY
    COMMENT = 'Red Bull online food-delivery analytics platform';

USE DATABASE REDBULL_DELIVERY;

CREATE SCHEMA IF NOT EXISTS RAW      COMMENT = '1:1 landing zone, all-VARCHAR, append-only';
CREATE SCHEMA IF NOT EXISTS STAGING  COMMENT = 'Typed + cleaned (dbt)';
CREATE SCHEMA IF NOT EXISTS MARTS    COMMENT = 'Dimensional model (dbt)';
CREATE SCHEMA IF NOT EXISTS UTIL     COMMENT = 'Ops: load history, audit, policies';

------------------------------------------------------------------------------
-- Functional roles
------------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS RB_LOADER       COMMENT = 'Writes RAW only';
CREATE ROLE IF NOT EXISTS RB_TRANSFORMER  COMMENT = 'Reads RAW, owns STAGING + MARTS';
CREATE ROLE IF NOT EXISTS RB_ANALYST_HQ   COMMENT = 'Reads all MARTS, all markets';
CREATE ROLE IF NOT EXISTS RB_ANALYST_USA  COMMENT = 'Reads MARTS, USA only';
CREATE ROLE IF NOT EXISTS RB_ANALYST_GBR  COMMENT = 'Reads MARTS, GBR only';
CREATE ROLE IF NOT EXISTS RB_ANALYST_DEU  COMMENT = 'Reads MARTS, DEU only';

-- Role hierarchy -> SYSADMIN for admin visibility
GRANT ROLE RB_LOADER      TO ROLE SYSADMIN;
GRANT ROLE RB_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE RB_ANALYST_HQ  TO ROLE RB_TRANSFORMER;
GRANT ROLE RB_ANALYST_USA TO ROLE RB_ANALYST_HQ;
GRANT ROLE RB_ANALYST_GBR TO ROLE RB_ANALYST_HQ;
GRANT ROLE RB_ANALYST_DEU TO ROLE RB_ANALYST_HQ;

-- Let the current user assume the new roles for demos
SET me = CURRENT_USER();
GRANT ROLE RB_LOADER      TO USER IDENTIFIER($me);
GRANT ROLE RB_TRANSFORMER TO USER IDENTIFIER($me);
GRANT ROLE RB_ANALYST_HQ  TO USER IDENTIFIER($me);
GRANT ROLE RB_ANALYST_USA TO USER IDENTIFIER($me);
GRANT ROLE RB_ANALYST_GBR TO USER IDENTIFIER($me);
GRANT ROLE RB_ANALYST_DEU TO USER IDENTIFIER($me);

------------------------------------------------------------------------------
-- Warehouse grants
------------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE RB_LOAD_WH      TO ROLE RB_LOADER;
GRANT USAGE ON WAREHOUSE RB_TRANSFORM_WH TO ROLE RB_TRANSFORMER;
GRANT USAGE ON WAREHOUSE RB_BI_WH        TO ROLE RB_ANALYST_HQ;
GRANT USAGE ON WAREHOUSE RB_BI_WH        TO ROLE RB_ANALYST_USA;
GRANT USAGE ON WAREHOUSE RB_BI_WH        TO ROLE RB_ANALYST_GBR;
GRANT USAGE ON WAREHOUSE RB_BI_WH        TO ROLE RB_ANALYST_DEU;

------------------------------------------------------------------------------
-- Database / schema grants
------------------------------------------------------------------------------
GRANT USAGE ON DATABASE REDBULL_DELIVERY TO ROLE RB_LOADER;
GRANT USAGE ON DATABASE REDBULL_DELIVERY TO ROLE RB_TRANSFORMER;
GRANT USAGE ON DATABASE REDBULL_DELIVERY TO ROLE RB_ANALYST_HQ;
GRANT USAGE ON DATABASE REDBULL_DELIVERY TO ROLE RB_ANALYST_USA;
GRANT USAGE ON DATABASE REDBULL_DELIVERY TO ROLE RB_ANALYST_GBR;
GRANT USAGE ON DATABASE REDBULL_DELIVERY TO ROLE RB_ANALYST_DEU;

-- RB_LOADER: full control of RAW + UTIL (load history lives in UTIL)
GRANT ALL ON SCHEMA RAW  TO ROLE RB_LOADER;
GRANT ALL ON SCHEMA UTIL TO ROLE RB_LOADER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RAW  TO ROLE RB_LOADER;
GRANT ALL ON FUTURE TABLES IN SCHEMA UTIL TO ROLE RB_LOADER;
GRANT ALL ON ALL TABLES IN SCHEMA RAW  TO ROLE RB_LOADER;
GRANT ALL ON ALL TABLES IN SCHEMA UTIL TO ROLE RB_LOADER;

-- RB_TRANSFORMER: read RAW, own STAGING + MARTS + UTIL
GRANT USAGE ON SCHEMA RAW TO ROLE RB_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE RB_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW    TO ROLE RB_TRANSFORMER;
GRANT ALL ON SCHEMA STAGING TO ROLE RB_TRANSFORMER;
GRANT ALL ON SCHEMA MARTS   TO ROLE RB_TRANSFORMER;
GRANT ALL ON SCHEMA UTIL    TO ROLE RB_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA STAGING TO ROLE RB_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA STAGING TO ROLE RB_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA MARTS   TO ROLE RB_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS  IN SCHEMA MARTS   TO ROLE RB_TRANSFORMER;

-- Analysts: read MARTS only (row-level market filter added in 03_row_access_policies.sql)
GRANT USAGE ON SCHEMA MARTS TO ROLE RB_ANALYST_HQ;
GRANT USAGE ON SCHEMA MARTS TO ROLE RB_ANALYST_USA;
GRANT USAGE ON SCHEMA MARTS TO ROLE RB_ANALYST_GBR;
GRANT USAGE ON SCHEMA MARTS TO ROLE RB_ANALYST_DEU;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS TO ROLE RB_ANALYST_HQ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA MARTS TO ROLE RB_ANALYST_HQ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS TO ROLE RB_ANALYST_USA;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA MARTS TO ROLE RB_ANALYST_USA;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS TO ROLE RB_ANALYST_GBR;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA MARTS TO ROLE RB_ANALYST_GBR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS TO ROLE RB_ANALYST_DEU;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA MARTS TO ROLE RB_ANALYST_DEU;
